/*
 * Copyright (c) 2015 Yale University and others.  All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v1.0 which accompanies this distribution,
 * and is available at http://www.eclipse.org/legal/epl-v10.html
 */
package org.opendaylight.alto.commons;

import org.opendaylight.yang.gen.v1.urn.opendaylight.alto.service.types.rev141101.MediaType;

class YangModelMediaType {

    /** The media types generated by alto-model
     * */

    public static final String ALTO_DIRECTORY
                            = new MediaType(MediaType.Enumeration.AltoDirectory).toString();
    public static final String ALTO_NETWORKMAP
                            = new MediaType(MediaType.Enumeration.AltoNetworkmap).toString();
    public static final String ALTO_NETWORKMAP_FILTER
                            = new MediaType(MediaType.Enumeration.AltoNetworkmapfilter).toString();
    public static final String ALTO_COSTMAP
                            = new MediaType(MediaType.Enumeration.AltoCostmap).toString();
    public static final String ALTO_COSTMAP_FILTER
                            = new MediaType(MediaType.Enumeration.AltoCostmapfilter).toString();
    public static final String ALTO_ENDPOINT_PROP
                            = new MediaType(MediaType.Enumeration.AltoEndpointprop).toString();
    public static final String ALTO_ENDPOINT_PROPPARAMS
                            = new MediaType(MediaType.Enumeration.AltoEndpointpropparams).toString();
    public static final String ALTO_ENDPOINT_COST
                            = new MediaType(MediaType.Enumeration.AltoEndpointcost).toString();
    public static final String ALTO_ENDPOST_COSTPARAMS
                            = new MediaType(MediaType.Enumeration.AltoEndpointcostparams).toString();
    public static final String ALTO_ERROR
                            = new MediaType(MediaType.Enumeration.AltoError).toString();
}
