/*
* Generated file
*
* Generated from: yang module name: alto-provider-impl yang module local name: alto-provider-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Thu Nov 20 06:13:29 EST 2014
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.alto_provider.impl;
public class AltoProviderModuleFactory extends org.opendaylight.controller.config.yang.config.alto_provider.impl.AbstractAltoProviderModuleFactory {

}
