/*
 * Copyright (c) 2015 Yale University and others.  All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v1.0 which accompanies this distribution,
 * and is available at http://www.eclipse.org/legal/epl-v10.html
 */
package org.opendaylight.alto.commons.types.alto.model.rev141101;

class MediaType {

    /** The media types generated by alto-model
     * */

    public static final String ALTO_DIRECTORY
                            = new org.opendaylight.yang.gen.v1.urn.opendaylight.alto.service.types.rev141101.MediaType(
                                    org.opendaylight.yang.gen.v1.urn.opendaylight.alto.service.types.rev141101.MediaType.Enumeration.AltoDirectory
                                ).toString();

    public static final String ALTO_NETWORKMAP
                            = new org.opendaylight.yang.gen.v1.urn.opendaylight.alto.service.types.rev141101.MediaType(
                                    org.opendaylight.yang.gen.v1.urn.opendaylight.alto.service.types.rev141101.MediaType.Enumeration.AltoNetworkmap
                                ).toString();

    public static final String ALTO_NETWORKMAP_FILTER
                            = new org.opendaylight.yang.gen.v1.urn.opendaylight.alto.service.types.rev141101.MediaType(
                                    org.opendaylight.yang.gen.v1.urn.opendaylight.alto.service.types.rev141101.MediaType.Enumeration.AltoNetworkmapfilter
                                ).toString();

    public static final String ALTO_COSTMAP
                            = new org.opendaylight.yang.gen.v1.urn.opendaylight.alto.service.types.rev141101.MediaType(
                                    org.opendaylight.yang.gen.v1.urn.opendaylight.alto.service.types.rev141101.MediaType.Enumeration.AltoCostmap
                                ).toString();

    public static final String ALTO_COSTMAP_FILTER
                            = new org.opendaylight.yang.gen.v1.urn.opendaylight.alto.service.types.rev141101.MediaType(
                                    org.opendaylight.yang.gen.v1.urn.opendaylight.alto.service.types.rev141101.MediaType.Enumeration.AltoCostmapfilter
                                ).toString();

    public static final String ALTO_ENDPOINT_PROP
                            = new org.opendaylight.yang.gen.v1.urn.opendaylight.alto.service.types.rev141101.MediaType(
                                    org.opendaylight.yang.gen.v1.urn.opendaylight.alto.service.types.rev141101.MediaType.Enumeration.AltoEndpointprop
                                ).toString();

    public static final String ALTO_ENDPOINT_PROPPARAMS
                            = new org.opendaylight.yang.gen.v1.urn.opendaylight.alto.service.types.rev141101.MediaType(
                                    org.opendaylight.yang.gen.v1.urn.opendaylight.alto.service.types.rev141101.MediaType.Enumeration.AltoEndpointpropparams
                                ).toString();

    public static final String ALTO_ENDPOINT_COST
                            = new org.opendaylight.yang.gen.v1.urn.opendaylight.alto.service.types.rev141101.MediaType(
                                    org.opendaylight.yang.gen.v1.urn.opendaylight.alto.service.types.rev141101.MediaType.Enumeration.AltoEndpointcost
                                ).toString();

    public static final String ALTO_ENDPOST_COSTPARAMS
                            = new org.opendaylight.yang.gen.v1.urn.opendaylight.alto.service.types.rev141101.MediaType(
                                    org.opendaylight.yang.gen.v1.urn.opendaylight.alto.service.types.rev141101.MediaType.Enumeration.AltoEndpointcostparams
                                ).toString();

    public static final String ALTO_ERROR
                            = new org.opendaylight.yang.gen.v1.urn.opendaylight.alto.service.types.rev141101.MediaType(
                                    org.opendaylight.yang.gen.v1.urn.opendaylight.alto.service.types.rev141101.MediaType.Enumeration.AltoError
                                ).toString();

}
