/*
 * Copyright (c) 2015 Yale University and others.  All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v1.0 which accompanies this distribution,
 * and is available at http://www.eclipse.org/legal/epl-v10.html
 */

package org.opendaylight.alto.core.northbound.api.utils.rfc7285;

public class MediaType {

    /** The media types defined in [RFC7285]
     *
     *  The media types defined here should be identical to those
     *  generated by alto-model, the main reason we need this is
     *  the ones defined here are *STRING LITERALS*.
     * */

    public static final String ALTO_DIRECTORY
                            = "application/alto-directory+json";
    public static final String ALTO_NETWORKMAP
                            = "application/alto-networkmap+json";
    public static final String ALTO_NETWORKMAP_FILTER
                            = "application/alto-networkmapfilter+json";
    public static final String ALTO_COSTMAP
                            = "application/alto-costmap+json";
    public static final String ALTO_COSTMAP_FILTER
                            = "application/alto-costmapfilter+json";
    public static final String ALTO_ENDPOINT_PROP
                            = "application/alto-endpointprop+json";
    public static final String ALTO_ENDPOINT_PROPPARAMS
                            = "application/alto-endpointpropparams+json";
    public static final String ALTO_ENDPOINT_COST
                            = "application/alto-endpointcost+json";
    public static final String ALTO_ENDPOINT_COSTPARAMS
                            = "application/alto-endpointcostparams+json";
    public static final String ALTO_ERROR
                            = "application/alto-error+json";
}

